In [2]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import numpy as np

# write code below this line
wine = load_wine()
X, y = wine.data, wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

scaled_model = DecisionTreeClassifier(random_state=42)
scaled_model.fit(X_train_scaled, y_train)
predictions = scaled_model.predict(X_test_scaled)
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

diagonal_sum = np.diag(confusion_matrix).sum()
mistakes = np.size(y_test) - diagonal_sum
print(mistakes)

[[13  1  0]
 [ 0 14  0]
 [ 1  0  7]]
2
